load ../../src/test/performance_test/table_data_large/warehouse.csv into warehouse;
load ../../src/test/performance_test/table_data_large/item.csv into item;
load ../../src/test/performance_test/table_data_large/stock.csv into stock;
load ../../src/test/performance_test/table_data_large/district.csv into district;
load ../../src/test/performance_test/table_data_large/customer.csv into customer;
load ../../src/test/performance_test/table_data_large/history.csv into history;
load ../../src/test/performance_test/table_data_large/orders.csv into orders;
load ../../src/test/performance_test/table_data_large/new_orders.csv into new_orders;
load ../../src/test/performance_test/table_data_large/order_line.csv into order_line;